"""
Django settings for books_service project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
try:
    from decouple import config
except Exception:
    import os
    def config(key, default=None, cast=None):
        value = os.getenv(key, default)
        if cast and value is not None:
            try:
                return cast(value)
            except Exception:
                return value
        return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'books',
    'rest_framework',
    'import_export',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'books_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'books_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# ============================================
#    CORS CONFIGURATION
# ============================================
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = config(
        'CORS_ALLOWED_ORIGINS',
        default='http://localhost:3000',
        cast=lambda v: [s.strip() for s in v.split(',')]
    )
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'books.authentication.JWTAuthentication',
    ],
    
    # Default permission - require authentication for all endpoints
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    
    # Exception handling
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',

}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
#    MICROSERVICES CONFIGURATION
# ============================================

SERVICES = {
    'USER_SERVICE': config('USER_SERVICE_URL', default='http://localhost:8001'),
    'BOOK_SERVICE': config('BOOK_SERVICE_URL', default='http://localhost:8002'),
    'LOAN_SERVICE': config('LOAN_SERVICE_URL', default='http://localhost:8003'),
    'NOTIFICATION_SERVICE': config('NOTIFICATION_SERVICE_URL', default='http://localhost:8004'),
}

# ============================================
#    CONSUL CONFIGURATION
# ============================================

import socket
import sys
# Make sure we can import from common
sys.path.append(str(BASE_DIR.parent))
from common.consul_utils import get_ip_address

CONSUL_HOST = config('CONSUL_HOST', default='consul')
CONSUL_PORT = config('CONSUL_PORT', default=8500, cast=int)
SERVICE_NAME = 'books-service'
SERVICE_TAGS = ['books', 'backend']
SERVICE_ID = f"{SERVICE_NAME}-{socket.gethostname()}"
SERVICE_ADDRESS = config('SERVICE_ADDRESS', default=get_ip_address())
SERVICE_PORT = config('SERVICE_PORT', default=8002, cast=int) # Default Django port, typically overridden by env

# ============================================
#    AUTHENTICATION SETTINGS
# ============================================

# Timeout for user service calls (in seconds)
USER_SERVICE_TIMEOUT = config('USER_SERVICE_TIMEOUT', default=5, cast=int)

# Cache user validation results (optional - for performance)
USER_VALIDATION_CACHE_TTL = config('USER_VALIDATION_CACHE_TTL', default=300, cast=int)  # 5 minutes


