# Generated by Django 4.2.7 on 2025-11-24 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'book_reviews',
                'unique_together': {('book_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('category', models.CharField(choices=[('FICTION', 'Fiction'), ('NON_FICTION', 'Non-Fiction'), ('SCIENCE', 'Science'), ('TECHNOLOGY', 'Technologie'), ('HISTORY', 'Histoire'), ('BIOGRAPHY', 'Biographie'), ('CHILDREN', 'Enfants'), ('EDUCATION', 'Éducation'), ('POETRY', 'Poésie'), ('OTHER', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('cover_image_url', models.URLField(blank=True)),
                ('language', models.CharField(default='Français', max_length=50)),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('times_borrowed', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['isbn'], name='books_isbn_ce4a1a_idx'), models.Index(fields=['title'], name='books_title_7a737c_idx'), models.Index(fields=['author'], name='books_author_1c43f5_idx'), models.Index(fields=['category'], name='books_categor_9b5f05_idx')],
            },
        ),
    ]
