# Generated by Django 4.2.7 on 2025-12-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(choices=[('CREATED', 'Créé'), ('RENEWED', 'Renouvelé'), ('RETURNED', 'Retourné'), ('OVERDUE', 'Marqué en retard'), ('FINE_CALCULATED', 'Amende calculée'), ('FINE_PAID', 'Amende payée')], max_length=50)),
                ('performed_by', models.IntegerField(blank=True, help_text="ID de l'utilisateur qui a effectué l'action", null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Historique d'emprunt",
                'verbose_name_plural': "Historiques d'emprunts",
                'db_table': 'loan_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text="ID de l'utilisateur (User Service)")),
                ('book_id', models.IntegerField(db_index=True, help_text='ID du livre (Books Service)')),
                ('loan_date', models.DateField(auto_now_add=True, verbose_name="Date d'emprunt")),
                ('due_date', models.DateField(verbose_name='Date de retour prévue')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Date de retour réelle')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('RETURNED', 'Retourné'), ('OVERDUE', 'En retard'), ('RENEWED', 'Renouvelé')], default='ACTIVE', max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Montant de l'amende (DZD)")),
                ('fine_paid', models.BooleanField(default=False, verbose_name='Amende payée')),
                ('renewal_count', models.IntegerField(default=0, verbose_name='Nombre de renouvellements')),
                ('max_renewals', models.IntegerField(default=2, verbose_name='Nombre maximum de renouvellements')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'db_table': 'loans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='loans_user_id_b8d074_idx'), models.Index(fields=['book_id'], name='loans_book_id_5e4ebc_idx'), models.Index(fields=['status'], name='loans_status_9049a0_idx'), models.Index(fields=['due_date'], name='loans_due_dat_3e4b70_idx')],
            },
        ),
    ]
